version: '3'
services:
  superset:
    build:
      context: ./superset
      dockerfile: Dockerfile
    # command: ["superset", "run", "-p", "8088", "--with-threads", "--reload", "--debugger", "--host=0.0.0.0"]
    command: [
      "gunicorn",
      "--bind", "0.0.0.0:8088",
      "--access-logfile", "-",
      "--error-logfile", "-",
      "--workers", "5",
      "--worker-class", "gthread",
      "--threads", "10",
      "--timeout", "60",
      "--limit-request-line", "0",
      "--limit-request-field_size", "0",
      "app:app"
    ]
    env_file: superset/.env
    restart: always
    ports:
      - 8088:8088
    depends_on:
      - db
    volumes:
      - ./superset:/opt/project
    working_dir: /opt/project

  jupyter:
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    environment:
      JUPYTER_ENABLE_LAB: 1
    ports:
      - 8888:8888
    volumes:
      - ./volumes/jupyter-data:/home/jovyan/work
      - ./volumes/jupyter-conf:/home/jovyan/.jupyter
    command: start-notebook.sh --NotebookApp.token=''

  db:
    image: mysql:8.0.16
    restart: always
    env_file: superset/.env
    volumes:
      - ./volumes/mysql-data:/var/lib/mysql
      - ./volumes/mysql-conf:/etc/mysql/conf.d
      - ./volumes/mysql-init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
