version: '2'
services:
  server:
    image: redash/redash:6.0.0.b8537
    command: server
    depends_on:
      - postgres
      - redis
      - jupyter
      - db
    ports:
      - 5000:5000
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_COOKIE_SECRET: veryverysecret
      REDASH_WEB_WORKERS: 4
      REDASH_ADDITIONAL_QUERY_RUNNERS: "redash.query_runner.python"
    restart: always
    volumes:
      - ./volumes/server-data:/volumes
  worker:
    image: redash/redash:6.0.0.b8537
    command: scheduler
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      QUEUES: "queries,scheduled_queries,celery"
      WORKERS_COUNT: 2
      REDASH_ADDITIONAL_QUERY_RUNNERS: "redash.query_runner.python"
    restart: always
    volumes:
      - ./volumes/server-data:/volumes
  redis:
    image: redis:3.0-alpine
    restart: always
  postgres:
    image: postgres:9.5.6-alpine
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    restart: always
  jupyter:
    image: jupyter/datascience-notebook:abdb27a6dfbb
    environment:
      JUPYTER_ENABLE_LAB: 1
    ports:
      - 8888:8888
    volumes:
      - ./volumes/jupyter-data:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''
  db:
    image: mysql:8.0.16
    restart: always
    volumes:
      - ./volumes/mysql-data:/var/lib/mysql
      - ./volumes/mysql-conf:/etc/mysql/conf.d
      - ./volumes/mysql-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
