version: '2'
services:
  server:
    image: redash/redash:5.0.2.b5486
    command: server
    depends_on:
      - postgres
      - redis
      - jupyter
    ports:
      - 5000:5000
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_COOKIE_SECRET: veryverysecret
      REDASH_WEB_WORKERS: 4
    restart: always
  worker:
    image: redash/redash:5.0.2.b5486
    command: scheduler
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      QUEUES: "queries,scheduled_queries,celery"
      WORKERS_COUNT: 2
    restart: always
  redis:
    image: redis:3.0-alpine
    restart: always
  postgres:
    image: postgres:9.5.6-alpine
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    restart: always
  jupyter:
    image: jupyter/datascience-notebook:abdb27a6dfbb
    environment:
      JUPYTER_ENABLE_LAB: 1
    ports:
      - 8888:8888
    volumes:
      - ./volumes/jupyter-data:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''